Nistagram/Nistagram.Agents/Nistagram.Agents/Controllers/ItemsController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nistagram.Agents.Data;
using Nistagram.Agents.Models;
using Nistagram.Agents.Models.DTO;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Identity;

namespace Nistagram.Agents.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Cloudinary _cloudinary;
        private readonly UserManager<IdentityUser> _userManager;

        public ItemsController(ApplicationDbContext context, 
            Cloudinary cloudinary, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _cloudinary = cloudinary;
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Items
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(await _context.Item
                        .Where(x => x.AgentId == user.Id)
                        .ToListAsync());
        }

        //[Authorize(Policy = "BuyerPolicy")]
        // GET: Items
        public async Task<IActionResult> Shop()
        {
            return View(await _context.Item.ToListAsync());
        }

        [Authorize(Policy = "BuyerPolicy")]
        public async Task<IActionResult> PreviousCarts()
        {
            var user = await _userManager.GetUserAsync(User);

            Buyer buyer;
            if (_context.Buyer.Where(x => x.UserId == user.Id).Count() == 0)
            {
                buyer = new Buyer();
                buyer.UserId = user.Id;
                _context.Add(buyer);
                _context.SaveChanges();
            }
            else
            {
                buyer = _context.Buyer.Where(x => x.UserId == user.Id).FirstOrDefault();
            }

            var carts = _context.Cart
                .Where(x => x.BuyerId == buyer.Id && x.Id != buyer.CurrentCart)
                .ToList();

            return View("Carts", carts);
        }

        [Authorize(Policy = "BuyerPolicy")]
        public async Task<IActionResult> ViewCart(int id)
        {
            var cart = _context.Cart.Find(id);

            var itemIds = _context.CartItem
                .Where(x => x.CartId == cart.Id)
                .Select(x => x.ItemId)
                .ToList();

            var items = new List<Item>();

            foreach (var itemId in itemIds)
            {
                items.Add(_context.Item.Find(itemId));
            }

            return View(items);
        }

        [Authorize(Policy = "BuyerPolicy")]
        public async Task<IActionResult> Checkout()
        {
            var user = await _userManager.GetUserAsync(User);

            Buyer buyer;
            if (_context.Buyer.Where(x => x.UserId == user.Id).Count() == 0)
            {
                buyer = new Buyer();
                buyer.UserId = user.Id;
                _context.Add(buyer);
                _context.SaveChanges();
            }
            else
            {
                buyer = _context.Buyer.Where(x => x.UserId == user.Id).FirstOrDefault();
            }

            Cart cart;
            cart = new Cart();
            cart.BuyerId = buyer.Id;
            _context.Add(cart);
            _context.SaveChanges();
            buyer.CurrentCart = cart.Id;
            _context.Update(buyer);
            _context.SaveChanges();

            return View("Shop", await _context.Item.ToListAsync());
        }

        [Authorize(Policy = "BuyerPolicy")]
        public async Task<IActionResult> MyCart()
        {
            var user = await _userManager.GetUserAsync(User);

            Buyer buyer;
            if (_context.Buyer.Where(x => x.UserId == user.Id).Count() == 0)
            {
                buyer = new Buyer();
                buyer.UserId = user.Id;
                _context.Add(buyer);
                _context.SaveChanges();
            }
            else
            {
                buyer = _context.Buyer.Where(x => x.UserId == user.Id).FirstOrDefault();
            }

            Cart cart;

            if (buyer.CurrentCart == null || _context.Cart.Find(buyer.CurrentCart) == null)
            {
                cart = new Cart();
                cart.BuyerId = buyer.Id;
                _context.Add(cart);
                _context.SaveChanges();
                buyer.CurrentCart = cart.Id;
                _context.Update(buyer);
                _context.SaveChanges();
            }
            else
            {
                cart = _context.Cart.Find(buyer.CurrentCart);
            }

            var itemIds = _context.CartItem
                .Where(x => x.CartId == cart.Id)
                .Select(x => x.ItemId)
                .ToList();

            var items = new List<Item>();

            foreach (var itemId in itemIds)
            {
                items.Add(_context.Item.Find(itemId)); 
            }

            return View(items);
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Details/5
        public async Task<IActionResult> DeleteFromCart(int? id)
        {
            var user = await _userManager.GetUserAsync(User);

            Buyer buyer;
            if (_context.Buyer.Where(x => x.UserId == user.Id).Count() == 0)
            {
                buyer = new Buyer();
                buyer.UserId = user.Id;
                _context.Add(buyer);
                _context.SaveChanges();
            }
            else
            {
                buyer = _context.Buyer.Where(x => x.UserId == user.Id).FirstOrDefault();
            }

            int l = 0;
            //removes only first element with this id
            var cart = _context.Cart.Find(buyer.CurrentCart);
            var cartItem = _context.CartItem
                            .Where(x => x.ItemId == id && x.CartId == cart.Id)
                            .FirstOrDefault();
            if(cartItem != null)
            {
                _context.Remove(cartItem);
                _context.SaveChanges();
            }

            var itemIds = _context.CartItem
                .Where(x => x.CartId == cart.Id)
                .Select(x => x.ItemId)
                .ToList();

            var items = new List<Item>();

            foreach (var itemId in itemIds)
            {
                items.Add(_context.Item.Find(itemId));
            }

            return View("MyCart", items);
        }

        [HttpGet]
        [Authorize(Policy = "BuyerPolicy")]
        public async Task<IActionResult> AddToCart(int id)
        {
            var itemId = id;
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }
            if(_context.Item.Find(itemId) == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .FirstOrDefaultAsync(m => m.Id == itemId);

            if (item == null)
            {
                return NotFound();
            }

            Buyer buyer;
            if(_context.Buyer.Where(x => x.UserId == user.Id).Count() == 0)
            {
                buyer = new Buyer();
                buyer.UserId = user.Id;
                _context.Add(buyer);
                _context.SaveChanges();
            }
            else
            {
                buyer = _context.Buyer.Where(x => x.UserId == user.Id).FirstOrDefault();
            }

            Cart cart;
            if(buyer.CurrentCart == null || _context.Cart.Find(buyer.CurrentCart) == null)
            {
                cart = new Cart();
                cart.BuyerId = buyer.Id;
                _context.Add(cart);
                _context.SaveChanges();
                buyer.CurrentCart = cart.Id;
                _context.Update(buyer);
                _context.SaveChanges();
            }
            else
            {
                cart = _context.Cart.Find(buyer.CurrentCart);
            }

            CartItem ca = new CartItem();
            ca.CartId = cart.Id;
            ca.ItemId = item.Id;

            _context.Add(ca);
            _context.SaveChanges();

            return View("Shop", await _context.Item.ToListAsync());
        }


        [Authorize(Policy = "AgentPolicy")]
        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upload(int id)
        {
            ViewData["id"] = id;
            return View(new UploadFileDTO());
        }

        [HttpPost]
        public async Task<IActionResult> Upload(UploadFileDTO model)
        {
            if (model.MyImage != null)
            {
                if(_context.Item.Where(x => x.Id == model.ImageId).Count() == 0)
                {
                    return NotFound();
                }

                var item = _context.Item.Find(model.ImageId);

                var link = await UploadFileToCloudinary(model.MyImage);

                item.WebImageUri = link;

                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nistagram.Agents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nistagram Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if ((await AuthorizationService.AuthorizeAsync(User, null, "AdminPolicy")).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                </li>
                            }
                            @if ((await AuthorizationService.AuthorizeAsync(User, null, "AgentPolicy")).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Items" asp-action="Index">My items</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Promotions" asp-action="Index">Promotions</a>
                                </li>
                            }
                            @if ((await AuthorizationService.AuthorizeAsync(User, null, "BuyerPolicy")).Succeeded)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Items" asp-action="Shop">Shop</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Items" asp-action="Shop">Shop</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Nistagram.Agents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>