Nistagram/Nistagram.Agents/Nistagram.Agents/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Nistagram.Agents.Models
{
    public class Cart
    {
        [Key]
        public int Id { get; set; }
        public DateTime CreationTime { get; private set; }
        public int BuyerId { get; set; }

        public Cart()
        {
            CreationTime = DateTime.Now;
        }
    }
}

Nistagram/Nistagram.Agents/Nistagram.Agents/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Nistagram.Agents.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LocalImageUri { get; set; }
        public string WebImageUri { get; set; }
        public double Price { get; set; }
        public string AgentId { get; set; }
        public DateTime CreationTime { get; private set; }
        public Item()
        {
            CreationTime = DateTime.Now;
            WebImageUri = "https://i.pinimg.com/originals/ae/8a/c2/ae8ac2fa217d23aadcc913989fcc34a2.png";
        }
    }
}

Nistagram/Nistagram.Agents/Nistagram.Agents/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nistagram.Agents.Data;
using Nistagram.Agents.Models;

namespace Nistagram.Agents.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cart.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CreationTime")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CreationTime")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.Cart.FindAsync(id);
            _context.Cart.Remove(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(int id)
        {
            return _context.Cart.Any(e => e.Id == id);
        }
    }
}

Nistagram/Nistagram.Agents/Nistagram.Agents/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Nistagram.Agents.Data;
using Nistagram.Agents.Models;
using Nistagram.Agents.Models.DTO;

namespace Nistagram.Agents.Controllers
{
    public class PromotionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager; 
        private IHostingEnvironment _env;
        //private readonly HttpClient _httpClient;
        private string _nistagramApiPost = "https://localhost:5006/Marketing/Upload/";
        private string _nistagramApiGet = "https://localhost:5006/Marketing/Get/";

        public PromotionsController(ApplicationDbContext context, 
            UserManager<IdentityUser> userManager, IHostingEnvironment env)
            //, HttpClient client)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
            //_httpClient = client;
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Promotions
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(await _context.Promotion.Where(x => x.AgentId == user.Id).ToListAsync());
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Promotions/Details/5
        public async Task<IActionResult> Send(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (promotion == null)
            {
                return NotFound();
            }

            string json = JsonConvert.SerializeObject(promotion);
            HttpClient client = new HttpClient();

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, _nistagramApiPost);
            request.Headers.Add("jsonString", json);

            request.Content = new StringContent("OK", Encoding.UTF8, "text/plain");

            HttpResponseMessage response = await client.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string result = await response.Content.ReadAsStringAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SaveToXML(int id)
        {
            var promotions = new List<PromotionDTO>();
            var user = await _userManager.GetUserAsync(User);
            string url = _nistagramApiGet + user.Id;

            // usually you create on HttpClient per Application (it is the best practice)
            HttpClient client = new HttpClient();

            using (HttpResponseMessage response = client.GetAsync(url).Result)
            {
                using (HttpContent content = response.Content)
                {
                    var json = content.ReadAsStringAsync().Result;
                    promotions = JsonConvert.DeserializeObject<List<PromotionDTO>>(json);
                }
            }

            var promotion = promotions.Where(x => x.Id == id).FirstOrDefault();
            if (promotion == null)
                return NotFound();

            var extension = ".xml";
            var fileName = DateTime.Now.Ticks + extension; //Create a new Name for the file due to security reasons.

            var pathBuilt = Path.Combine(Directory.GetCurrentDirectory(), "Upload\\files");

            if (!Directory.Exists(pathBuilt))
            {
                Directory.CreateDirectory(pathBuilt);
            }

            XmlSerializer xs = new XmlSerializer(typeof(PromotionDTO));

            TextWriter txtWriter = new StreamWriter(pathBuilt + "\\" + fileName);

            var fileFullPath = pathBuilt + "\\" + fileName;

            xs.Serialize(txtWriter, promotion);

            txtWriter.Close();

            var encodedPath = fileFullPath.Replace(":\\", "~~~").Replace("\\", "~~");

            using (HttpResponseMessage response = client.PostAsync("http://localhost:5000/api/" + encodedPath, null).Result)
            {
                using (HttpContent content = response.Content)
                {
                    var json = content.ReadAsStringAsync().Result;
                }
            }

            return RedirectToAction("ViewPromotions");
        }

        public async Task<IActionResult> ViewPromotions()
        {
            var promotions = new List<PromotionDTO>();
            var user = await _userManager.GetUserAsync(User);
            string url = _nistagramApiGet + user.Id;

            // usually you create on HttpClient per Application (it is the best practice)
            HttpClient client = new HttpClient();
            
            using (HttpResponseMessage response = client.GetAsync(url).Result)
            {
                using (HttpContent content = response.Content)
                {
                    var json = content.ReadAsStringAsync().Result;
                    promotions = JsonConvert.DeserializeObject<List<PromotionDTO>>(json);
                }
            }
            return View(promotions);
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Promotions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion
                .FirstOrDefaultAsync(m => m.Id == id);
            if (promotion == null)
            {
                return NotFound();
            }

            ViewData["json"] = JsonConvert.SerializeObject(promotion);

            return View(promotion);
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Promotions/Create
        public async Task<IActionResult> Create(int id)
        {
            var user = await _userManager.GetUserAsync(User);

            var item = _context.Item.Find(id);
            if (item == null)
                return NotFound();

            ViewData["imageUrl"] = item.WebImageUri;

            Promotion promotion = new Promotion();
            promotion.AgentId = user.Id;
            promotion.Start = DateTime.Now;
            promotion.End = DateTime.Now;
            promotion.ImageUrl = item.WebImageUri;
            promotion.TargetUrl = "https://localhost:44339/Items/Details/" + id.ToString();

            return View(promotion);
        }

        // POST: Promotions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AgentPolicy")]
        public async Task<IActionResult> Create([Bind("Id,Name,Start,End,MinAge,MaxAge,TargetUrl,ImageUrl,AgentId")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                Promotion p = new Promotion();
                p.AgentId = promotion.AgentId;
                p.End = promotion.End;
                p.Start = promotion.Start;
                p.ImageUrl = promotion.ImageUrl;
                p.MaxAge = promotion.MaxAge;
                p.MinAge = promotion.MinAge;
                p.Name = promotion.Name;
                p.TargetUrl = promotion.TargetUrl;

                _context.Add(p);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }

        [Authorize(Policy = "AgentPolicy")]
        // GET: Promotions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion.FindAsync(id);
            if (promotion == null)
            {
                return NotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AgentPolicy")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Start,End,MinAge,MaxAge,TargetUrl,ImageUrl,AgentId")] Promotion promotion)
        {
            if (id != promotion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(promotion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PromotionExists(promotion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(promotion);
        }

        // GET: Promotions/Delete/5
        [Authorize(Policy = "AgentPolicy")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promotion = await _context.Promotion

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Carts.cshtml
@model IEnumerable<Nistagram.Agents.Models.Cart>

@{
    ViewData["Title"] = "Previous carts";
}

<h1>Previous carts</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreationTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationTime)
                </td>
                <td>
                    <a asp-action="ViewCart" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Create.cshtml
@model Nistagram.Agents.Models.DTO.ItemDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Delete.cshtml
@model Nistagram.Agents.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalImageUri)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalImageUri)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebImageUri)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebImageUri)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Details.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@model Nistagram.Agents.Models.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <img src="@Html.DisplayFor(model => model.WebImageUri)" style="max-height: 200px;max-width: 200px" />
    </dl>
</div>
<div>
    @if (SignInManager.IsSignedIn(User))
    {
        @if ((await AuthorizationService.AuthorizeAsync(User, null, "AgentPolicy")).Succeeded)
        {
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> 
            <a asp-controller="Promotions" asp-action="Create" asp-route-id="@Model.Id">Create promotion</a>
            <a asp-action="Index"> Back to List</a>
        }
        else if ((await AuthorizationService.AuthorizeAsync(User, null, "BuyerPolicy")).Succeeded)
        {
            <a asp-action="AddToCart" asp-route-id="@Model.Id">Add to cart</a>
            <a asp-action="Shop"> Back to List</a>
        }
    }
</div>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Edit.cshtml
@model Nistagram.Agents.Models.Item

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <a asp-action="Upload" asp-route-id="@ViewData["id"]">Add photo</a> |

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Index.cshtml
@model IEnumerable<Nistagram.Agents.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/MyCart.cshtml
@model IEnumerable<Nistagram.Agents.Models.Item>

@{
    ViewData["Title"] = "Shop";
}

<h1>ViewCart</h1>

<h2>Number of items: @Model.Count()</h2>
<h2>Total cost: @Model.Sum(x => x.Price)</h2>

<a asp-action="Checkout">Checkout</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.WebImageUri)" style="max-height:80px; max-width:80px" \ />
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>

                    <a asp-action="DeleteFromCart" asp-route-id="@item.Id">Delete from cart</a>
                </td>
            </tr>
        }
    </tbody>

    <a asp-action="PreviousCarts">My previous carts</a>
</table>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Shop.cshtml
@model IEnumerable<Nistagram.Agents.Models.Item>

@{
    ViewData["Title"] = "Shop";
}

<h1>Shop</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.WebImageUri)" style="max-height:80px; max-width:80px" \ />
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/Upload.cshtml
@model Nistagram.Agents.Models.DTO.UploadFileDTO

<form asp-action="Upload" enctype="multipart/form-data">
    Image Id: @ViewData["id"]
    <input asp-for="MyImage" />
    <input asp-for="ImageId" value='@ViewData["id"]' hidden/>

    <input type="submit" />
</form>

Nistagram/Nistagram.Agents/Nistagram.Agents/Views/Items/ViewCart.cshtml
@model IEnumerable<Nistagram.Agents.Models.Item>

@{
    ViewData["Title"] = "Cart";
}

<h1>ViewCart</h1>

<h2>Number of items: @Model.Count()</h2>
<h2>Total cost: @Model.Sum(x => x.Price)</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.WebImageUri)" style="max-height:80px; max-width:80px" \ />
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>

                </td>
            </tr>
        }
    </tbody>
</table>